#!/bin/bash
# memory-archive.sh - 记忆归档脚本
# 每3天运行一次，整理记忆文件

set -e

WORKSPACE="/Users/jiangcong/.openclaw/workspace"
MEMORY_DIR="$WORKSPACE/memory"
MEMORY_FILE="$WORKSPACE/MEMORY.md"
DATE=$(date +%Y-%m-%d)
DATETIME=$(date '+%Y-%m-%d %H:%M:%S')

echo "[$DATETIME] 开始记忆整理..."

# 1. 检查是否有需要归档的文件（3天前的文件）
cd "$MEMORY_DIR"
ARCHIVE_FILES=$(find . -name "*.md" -type f -mtime +3 2>/dev/null || true)

if [ -z "$ARCHIVE_FILES" ]; then
    echo "没有需要归档的文件（3天前的记忆）"
else
    echo "发现需要归档的文件:"
    echo "$ARCHIVE_FILES"
    
    # 2. 提取重要信息到长期记忆
    echo "提取重要信息到 MEMORY.md..."
    
    # 创建临时文件存储新摘要
    TEMP_SUMMARY=$(mktemp)
    echo "" >> "$TEMP_SUMMARY"
    echo "### $DATE 归档摘要" >> "$TEMP_SUMMARY"
    echo "" >> "$TEMP_SUMMARY"
    
    for file in $ARCHIVE_FILES; do
        # 提取文件名中的日期
        FILE_DATE=$(basename "$file" .md | sed 's/^\.\///')
        echo "- **$FILE_DATE**: 已归档到 GitHub" >> "$TEMP_SUMMARY"
    done
    
    echo "" >> "$TEMP_SUMMARY"
    
    # 将摘要插入到 MEMORY.md 的"重要信息摘要"部分之后
    if grep -q "## 重要信息摘要" "$MEMORY_FILE"; then
        awk -v summary="$TEMP_SUMMARY" '
            /^## 重要信息摘要/ { found=1 }
            found && /^$/ && !inserted {
                while ((getline line < summary) > 0) {
                    print line
                }
                close(summary)
                inserted=1
            }
            { print }
        ' "$MEMORY_FILE" > "$MEMORY_FILE.tmp" && mv "$MEMORY_FILE.tmp" "$MEMORY_FILE"
    fi
    
    rm -f "$TEMP_SUMMARY"
    
    # 3. 更新最近3天文件列表
    echo "更新最近3天记录..."
    
    RECENT_FILES=$(find "$MEMORY_DIR" -name "*.md" -type f -mtime -4 | sort -r | head -3)
    
    TEMP_SECTION=$(mktemp)
    echo "" >> "$TEMP_SECTION"
    echo "## 最近3天原始记录" >> "$TEMP_SECTION"
    echo "" >> "$TEMP_SECTION"
    
    for file in $RECENT_FILES; do
        FILE_NAME=$(basename "$file")
        FILE_DATE=$(basename "$file" .md)
        echo "### $FILE_DATE" >> "$TEMP_SECTION"
        echo "- [完整记录: memory/$FILE_NAME]" >> "$TEMP_SECTION"
        echo "" >> "$TEMP_SECTION"
    done
    
    # 替换 MEMORY.md 中的最近3天部分
    awk -v section="$TEMP_SECTION" '
        /^## 最近3天原始记录/ { 
            skip=1
            while ((getline line < section) > 0) {
                print line
            }
            close(section)
            next
        }
        skip && /^## / { skip=0 }
        !skip { print }
    ' "$MEMORY_FILE" > "$MEMORY_FILE.tmp" && mv "$MEMORY_FILE.tmp" "$MEMORY_FILE"
    
    rm -f "$TEMP_SECTION"
    
    # 4. GitHub 提交
    echo "提交到 GitHub..."
    cd "$WORKSPACE"
    
    git config user.email "openclaw@local" 2>/dev/null || true
    git config user.name "OpenClaw Memory Bot" 2>/dev/null || true
    
    git add memory/
    git add MEMORY.md
    
    if git diff --cached --quiet; then
        echo "没有变更需要提交"
    else
        git commit -m "📚 Memory archive: $DATE

- Archived old memory files (3+ days)
- Updated MEMORY.md summaries
- Auto-generated by memory-archive script"
        
        if git remote get-url origin >/dev/null 2>&1; then
            git push origin main 2>/dev/null || git push origin master 2>/dev/null || echo "推送失败，请检查 GitHub 配置"
        else
            echo "警告: 没有配置远程仓库"
        fi
    fi
    
    # 5. 删除已归档的本地文件
    echo "清理旧文件..."
    find "$MEMORY_DIR" -name "*.md" -type f -mtime +3 -delete
    
    echo "归档完成！"
fi

echo "{\"lastArchive\": \"$DATETIME\"}" > "$WORKSPACE/memory/.last-archive.json"

echo "[$DATETIME] 记忆整理完成"
